// Task # 23
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car !== 'subaru'? I predict false.");
console.log(car !== 'subaru');
console.log("Is car == 'Honda Civic'? I predict false.");
console.log(car == 'Honda Civic');
console.log("Is car !== 'Honda Civic'? I predict True.");
console.log(car !== 'Honda Civic');
console.log("Is car == 'Audi A4'? I predict false.");
console.log(car == 'Audi A4');
console.log("Is car !== 'Audi A4'? I predict True.");
console.log(car !== 'Audi A4');
console.log("Is car == 'Ford Mustang'? I predict false.");
console.log(car == 'Ford Mustang');
console.log("Is car !== 'Ford Mustang'? I predict True.");
console.log(car !== 'Ford Mustang');
console.log("Is car == 'Subaru Impreza'? I predict false.");
console.log(car == 'Subaru Impreza');
console.log("Is car !== 'Subaru Impreza'? I predict True.");
console.log(car !== 'Subaru Impreza');
console.log("Is car == 'Honda Accord'? I predict false.");
console.log(car == 'Honda Accord');
console.log("Is car !== 'Honda Accord'? I predict True.");
console.log(car !== 'Honda Accord');
export {};
